wallpaper {
    # monitor = DP-2
    monitor = eDP-1
    path = /home/brandon/desktop/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/brandon/desktop/background.jpg
    fit_mode = cover
}
