-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(2fafff)",
			inactive_border = "rgb(646464)",
		},
	},
	group = {
		col = {
			border_active = "rgb(2fafff)",
			border_inactive = "rgb(646464)",
			border_locked_active = "rgb(ff5f59)",
			border_locked_inactive = "rgb(646464)",
		},
		groupbar = {
			col = {
				active = "rgb(2fafff)",
				inactive = "rgb(646464)",
				locked_active = "rgb(ff5f59)",
				locked_inactive = "rgb(646464)",
			},
		},
	},
})
