-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(0031a9)",
			inactive_border = "rgb(9f9f9f)",
		},
	},
	group = {
		col = {
			border_active = "rgb(0031a9)",
			border_inactive = "rgb(9f9f9f)",
			border_locked_active = "rgb(a60000)",
			border_locked_inactive = "rgb(9f9f9f)",
		},
		groupbar = {
			col = {
				active = "rgb(0031a9)",
				inactive = "rgb(9f9f9f)",
				locked_active = "rgb(a60000)",
				locked_inactive = "rgb(9f9f9f)",
			},
		},
	},
})
