# -----------------------------
# 🍺 Brew taps
# -----------------------------
tap "d12frosted/emacs-plus"
tap "borkdude/brew"

# -----------------------------
# 🔧 CLI tools & developer stuff
# -----------------------------

brew "act"
brew "mise"
brew "awscli"
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "bat"
brew "bun"
brew "cmake"
brew "libtool"
brew "libyaml" # necessary for Ruby
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "htop"
brew "neovim"
brew "ripgrep"
brew "tree"
brew "tree-sitter"
brew "cloc"
brew "curl"

# JDK / JRE / Clojure stuff
brew "openjdk"
brew "clojure"

# Node-related build support (optional, uncomment if needed)
# brew "pkg-config"
# brew "cairo"
# brew "pango"
# brew "libpng"
# brew "libjpeg"
# brew "giflib"
# brew "librsvg"
# brew "pixman"

# These are deps for the Mise Postgres plugin
brew 'gcc'
brew 'readline'
brew 'zlib'
brew 'curl'
brew 'ossp-uuid'
brew 'icu4c'
brew 'pkg-config'

# -----------------------------
# 📦 Special brews from taps
# -----------------------------

brew "d12frosted/emacs-plus/emacs-plus", args: [
  "with-retro-gnu-meditate-levitate-icon",
  "with-dbus"
]
